param(
    [switch]$Synchronous
)

$ErrorActionPreference = "Stop"

# Resolve the repository root so the hook is installed into the correct .git directory.
function Get-RepoRoot {
    $scriptDir = Split-Path -Parent $PSCommandPath
    return (Resolve-Path (Join-Path $scriptDir "..")).Path
}

# Generate a Git Bash compatible post-commit hook.
function New-PostCommitHookContent {
    param([bool]$RunSynchronously)

    $modeLine = if ($RunSynchronously) {
        'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$repo_root/scripts/local-release-pipeline.ps1" -Reason post-commit >> "$log_file" 2>&1'
    } else {
        'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$repo_root/scripts/local-release-pipeline.ps1" -Reason post-commit >> "$log_file" 2>&1 &'
    }

    return @(
        "#!/bin/sh",
        "# Auto-generated by scripts/install-local-release-hook.ps1.",
        "# Runs the local CCSwitchMulti release pipeline after every successful commit.",
        "repo_root=`$(git rev-parse --show-toplevel)",
        "log_dir=`"$repo_root/scripts/logs`"",
        "mkdir -p `"$log_dir`"",
        "log_file=`"$log_dir/post-commit-release.log`"",
        "echo `"[`$(date '+%Y-%m-%d %H:%M:%S')] post-commit release triggered for `$(git rev-parse --short HEAD)`" >> `"$log_file`"",
        $modeLine
    ) -join "`n"
}

$repoRoot = Get-RepoRoot
$hooksDir = Join-Path $repoRoot ".git\hooks"
$hookPath = Join-Path $hooksDir "post-commit"

if (-not (Test-Path -LiteralPath $hooksDir)) {
    throw "Git hooks directory not found: $hooksDir"
}

$content = New-PostCommitHookContent -RunSynchronously:$Synchronous.IsPresent
Set-Content -LiteralPath $hookPath -Value $content -Encoding ASCII

Write-Host "Installed local release post-commit hook: $hookPath"
if ($Synchronous) {
    Write-Host "Mode: synchronous. git commit waits until packaging finishes."
} else {
    Write-Host "Mode: background. git commit returns immediately; logs go to scripts/logs/post-commit-release.log."
}
